jobs:
  main-ci:
    name: Main CI
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        name: Install dependencies
        run: npm ci
      - name: Run linting processes
        run: npm run lint
      - name: Run build processes
        run: npm run build
      - name: Create release ZIP
        run: |
          mkdir -p release
          zip -r release/${GITHUB_REPOSITORY#*/}.zip dist images .env.example CHANGELOG.md LICENSE package-lock.json package.json readme.md
      - env:
          GITHUB_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        id: semantic
        name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branches: |
            [
              'main'
            ]
          extra_plugins: |
            @semantic-release/commit-analyzer@13.0.1
            @semantic-release/changelog@6.0.3
            @semantic-release/github@11.0.1
            @semantic-release/release-notes-generator@14.0.3
      - name: Upload release asset
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: release/${GITHUB_REPOSITORY#*/}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
name: Main Commit
on:
  push:
    branches:
      - main
