jobs:
  main-ci:
    name: Main CI
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        name: Install dependencies
        run: npm ci
      - name: Run linting processes
        run: npm run lint
      - name: Run build processes
        run: npm run build
      - env:
          GITHUB_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        id: semantic
        name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branches: |
            [
              'main'
            ]
          extra_plugins: |
            @semantic-release/commit-analyzer@13.0.1
            @semantic-release/github@11.0.1
            @semantic-release/release-notes-generator@14.0.3
      - if: steps.semantic.outputs.new_release_published == 'true'
        name: Create release asset
        run: |
          mkdir -p release
          zip -r release/artifact.zip dist images .env.example LICENSE package-lock.json package.json readme.md
      - env:
          GITHUB_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        if: steps.semantic.outputs.new_release_published == 'true'
        name: Get release ID
        run: |
          RELEASE_TAG=${{ steps.semantic.outputs.new_release_git_tag }}
          RELEASE_ID=$(gh api repos/${{ github.repository }}/releases/tags/$RELEASE_TAG --jq '.id')
          echo "release_id=$RELEASE_ID" >> $GITHUB_ENV
      - env:
          GITHUB_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        if: steps.semantic.outputs.new_release_published == 'true'
        name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.release_id }}/assets{?name,label}
          asset_path: release/artifact.zip
          asset_name: ${{ github.repository | split('/')[-1] }}-${{ steps.semantic.outputs.new_release_version }}.zip
          asset_content_type: application/zip
name: Main Commit
on:
  push:
    branches:
      - main
