jobs:
  main-ci:
    name: Main CI
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - env:
          GITHUB_TOKEN: ${{ secrets.CI_ACCESS_TOKEN }}
        id: semantic
        name: Run Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          branches: |
            [
              'main'
            ]
          extra_plugins: |
            @semantic-release/commit-analyzer@13.0.1
            @semantic-release/changelog@6.0.3
            @semantic-release/git@10.0.1
            @semantic-release/github@11.0.1
            @semantic-release/release-notes-generator@14.0.3
name: Main Commit
on:
  push:
    branches:
      - main
